# Generated by Django 5.2.15 on 2026-09-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_accountidentity"),
        ("idp", "0002_alter_oidctoken_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="oidctoken",
            name="subject",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
