# Generated by Django 5.2.15 on 2026-09-23 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def freeze_existing_principals(apps, schema_editor):
    alias = schema_editor.connection.alias
    account = apps.get_model(settings.AUTH_USER_MODEL)
    email_address = apps.get_model("account", "EmailAddress")
    identity = apps.get_model("updspaceid", "User")
    binding = apps.get_model("accounts", "AccountIdentity")
    for user in account.objects.using(alias).all().iterator():
        email = (user.email or "").strip().lower()
        verified = (
            email
            and email_address.objects.using(alias)
            .filter(user_id=user.pk, email__iexact=email, primary=True, verified=True)
            .exists()
        )
        candidate = None
        if (
            not verified
            and identity.objects.using(alias).filter(email__iexact=email).exists()
        ):
            # Runtime resolution remains blocked until ownership is proven.
            # Do not convert an unverified legacy email match into a durable link.
            continue
        if verified:
            if (
                account.objects.using(alias)
                .filter(email__iexact=email)
                .exclude(pk=user.pk)
                .exists()
            ):
                raise RuntimeError(
                    "Ambiguous identity ownership; review verified account emails before migration"
                )
            candidates = list(
                identity.objects.using(alias).filter(email__iexact=email)[:2]
            )
            if len(candidates) > 1:
                raise RuntimeError(
                    "Ambiguous master identity email; review before migration"
                )
            candidate = candidates[0] if candidates else None
        # Legacy OIDC used an exact lookup against the normalized email.
        subject = (
            str(candidate.pk)
            if candidate and candidate.email == email
            else str(user.pk)
        )
        binding.objects.using(alias).create(
            user_id=user.pk,
            identity_id=candidate.pk if candidate else None,
            public_subject=subject,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_country_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0009_emailaddress_unique_primary_email"),
        ("updspaceid", "0004_magiclink_skip_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountIdentity",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="identity_binding",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "public_subject",
                    models.CharField(editable=False, max_length=128, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "identity",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_binding",
                        to="updspaceid.user",
                    ),
                ),
            ],
        ),
        migrations.RunPython(freeze_existing_principals, migrations.RunPython.noop),
    ]
